### ISSUE TITLE
Unable to find daemon modules while using lunchy

### ISSUE THREAD

**Issue by shaunstanislaus** [eddiezane/lunchy#69]
```bash
┌-(~)-∞
└> ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
/Users/shaunstanislaus/Library/LaunchAgents -> /usr/local/opt/redis/homebrew.mxcl.redis.plist
┌-(~)-∞
└> lunchy start redis
No daemon found matching 'redis'

└> lunchy list
HWPortCfg
at.obdev.LittleSnitchUIAgent
com.google.keystone.agent
com.oracle.java.Java-Updater
com.paragon-software.NTFS.fsnotifyagent
com.paragon.updater
com.pgp.pgpengine
com.teamviewer.teamviewer
com.teamviewer.teamviewer_desktop
org.macosforge.xquartz.startx

```

is not found in the list either.

@bunnymatic , could you help me out again? previously you gave the command it worked, now it does not work at all. #61

**Comment by shaunstanislaus** [comment]
Resolved.

**Comment by CosmicCoder96** [comment]
@shaunstanislaus how did you resolve it?

**Comment by bunnymatic** [comment]
Here was the previous issue you filed and where I think I helped out.  https://github.com/eddiezane/lunchy/issues/65 
Though that doesn't look like the issue here.  

Did you check to see that the new redis plist file link worked properly?  You should be able to see a file `/Users/shaunstanislaus/Library/LaunchAgents/homebrew.mxcl.redis.plist` on your system.  
Also, did you run `launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist`?

Instead of linking the file as you did, you could use `lunchy install <plist-file>`

Hope this helps.

Also... moving forward, `homebrew-services` (https://github.com/Homebrew/homebrew-services) is definitely another option for managing your services on a mac.

**Comment by shaunstanislaus** [comment]
@bunnymatic wow you took almost a year to reply!

**Comment by bunnymatic** [comment]
I know.  I think it's because it said "resolved".  Then we got a comment
from someone about 'how it was resolved', so i thought i ought to do
something.

:)  sorry for the very very very late response.
